Hw02 express
anna-stasya/nodejs-REST-API pull request #1
Opened 2021-11-04 22:02 UTC by anna-stasya

Готово. Без разделения кода

2021-11-05 19:19 UTC, KirillKulakow commented on model/index.js
> +const readContact = async () => {
насколько понятно из функции то ты берешь контакты а не один контакт - может переименовать в readContacts

2021-11-05 19:20 UTC, KirillKulakow commented on model/index.js
> +const updateContact = async (newContact) => {
так же можно переименовать

2021-11-05 19:21 UTC, KirillKulakow commented on model/index.js
> +  const result = contact.find((item) => item.id === +contactId)
у тебя в json есть контакт с ид в виде строки - ты его не найдешь при сравнении item.id === +contactId

2021-11-05 19:21 UTC, KirillKulakow commented on model/index.js
> +  //   return null
почему закомментировано?

2021-11-05 19:22 UTC, KirillKulakow commented on model/index.js
> +  const contact = await readContact()
точно также как и в самом верху - ты получаешь не один контакт а несколько

2021-11-05 19:22 UTC, KirillKulakow commented on model/index.js
> +  const contact = await readContact()
лучше переименовать

2021-11-05 19:23 UTC, KirillKulakow commented on model/index.js
> +  const contact = await readContact()
также

2021-11-05 19:23 UTC, KirillKulakow commented on model/index.js
> +  const idx = contact.findIndex((item) => item.id === +contactId)
точно также - контакт с ид в виде строки не будет найден

2021-11-05 19:23 UTC, KirillKulakow commented on model/index.js
> +  console.log(body)
удалить

2021-11-05 19:24 UTC, KirillKulakow commented on model/index.js
> +  const idx = contact.findIndex(item => item.id === +contactId)
поправить

2021-11-05 19:36 UTC, KirillKulakow commented on model/index.js
> +  if (!body) {
зачем данная проверка - если ты можешь валидацию проводить через joi (комментарий в схеме оставлю)

2021-11-05 19:37 UTC, KirillKulakow commented on model/index.js
> +  contact[idx] = { ...body, contactId }
ты здесь полностью перезаписываешь контакт - поправь логику

2021-11-05 19:39 UTC, KirillKulakow commented on routes/api/contacts.js
> +})
в конце можно добавить .or('name', 'email', 'phone')

2021-11-05 19:41 UTC, KirillKulakow commented on routes/api/contacts.js
> +    console.log(error)
удалить

2021-11-05 19:42 UTC, KirillKulakow commented on routes/api/contacts.js
> +      message: 'Update contacts',
данный метод изменяет один контакт

2021-11-05 19:43 UTC, KirillKulakow requested changes
Need fix

2021-11-06 00:31 UTC, anna-stasya reviewed
внесла все правки

2021-11-06 00:31 UTC, anna-stasya commented on routes/api/contacts.js
> +      message: 'Update contacts',
изменила сообщение на более логичное

2021-11-06 00:31 UTC, anna-stasya commented on routes/api/contacts.js
> +    console.log(error)
удалила console.log(error)

2021-11-06 00:31 UTC, anna-stasya commented on routes/api/contacts.js
> +})
добавила  .or('name', 'email', 'phone') в joiSchemaUpdate

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  contact[idx] = { ...body, contactId }
изменила

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const idx = contact.findIndex(item => item.id === +contactId)
исправила, если будет строчный id

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  if (!body) {
удалила проверку

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  console.log(body)
удалила console.log(body)

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const idx = contact.findIndex((item) => item.id === +contactId)
исправила, id в виде строки будет удалено

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const contact = await readContact()
переименовала c readContact на readContacts

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const contact = await readContact()
переименовала c readContact на readContacts

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  //   return null
исправила

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const result = contact.find((item) => item.id === +contactId)
исправила функцию, теперь найдет id в виде строки

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +  const contact = await readContact()
Переименовала название функции на более логичное

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +const updateContact = async (newContact) => {
Переименовала название функции на более логичное

2021-11-06 00:31 UTC, anna-stasya commented on model/index.js
> +const readContact = async () => {
Переименовала название функции на более логичное

2021-11-06 10:13 UTC, KirillKulakow commented on model/index.js
> +  const contact = await readContact()
я имел ввиду const contacts

2021-11-06 10:15 UTC, KirillKulakow approved these changes

2021-11-06 22:02 UTC, anna-stasya commented on model/index.js
> +  const contact = await readContact()
везде изменила

2021-11-06 22:03 UTC, merged