done
anna-stasya/nodejs-REST-API pull request #3
Opened 2021-11-23 09:57 UTC by anna-stasya

2021-11-23 19:26 UTC, KirillKulakow commented on middelevwares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
вот здесь может быть ошибка - если ты без авторизации делаешь запрос

2021-11-23 19:34 UTC, KirillKulakow commented on controllers/auth/signup.js
> +    // res.status(409).json({
это удалить

2021-11-23 19:34 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  // const hashPassword = bcrypt.hashSync(password, salt)
и это

2021-11-23 19:34 UTC, KirillKulakow requested changes
need fix

2021-11-23 21:55 UTC, anna-stasya commented on middelevwares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
добавила проверку

2021-11-23 21:55 UTC, anna-stasya commented on controllers/auth/signup.js
> +    // res.status(409).json({
ой, исправила)

2021-11-23 21:55 UTC, anna-stasya commented on controllers/auth/signup.js
> +  // const hashPassword = bcrypt.hashSync(password, salt)
и тут

2021-11-24 20:29 UTC, KirillKulakow commented on routes/api/auth.js
> +router.post('/logout', authenticate, validation(joiSchema), controllerWrapper(logout))
пропущен шаг 5

2021-11-24 20:35 UTC, KirillKulakow commented
было бы не плохо сделать поиск контакта/удаление/обновление вместе с ид собственника, чтобы эти операции можно было проводить только собственнику контакта

2021-11-25 17:52 UTC, anna-stasya commented on routes/api/auth.js
> +router.post('/logout', authenticate, validation(joiSchema), controllerWrapper(logout))
да, я так рада, что все исправила и работает) уже добавила

2021-11-25 20:55 UTC, KirillKulakow commented on model/contacts.js
> +  const result = await Contact.findById(contactId, userId)
этот метод так не работает он ищет только по полю _id
используй findOne

2021-11-25 20:55 UTC, KirillKulakow commented on model/contacts.js
>    const result = await Contact.findByIdAndUpdate(
такой же коммент как выше

2021-11-25 20:55 UTC, KirillKulakow commented on model/contacts.js
> +  const result = await Contact.findByIdAndRemove({ _id: contactId, owner: userId })
такой же коммент как выше

2021-11-25 20:55 UTC, KirillKulakow commented on model/contacts.js
>    const result = await Contact.findByIdAndUpdate(
такой же коммент как выше

2021-11-25 20:55 UTC, KirillKulakow requested changes
Need fix

2021-11-25 23:08 UTC, anna-stasya commented on model/contacts.js
> +  const result = await Contact.findById(contactId, userId)
спасибо, исправила

2021-11-25 23:08 UTC, anna-stasya commented on model/contacts.js
>    const result = await Contact.findByIdAndUpdate(
исправила

2021-11-25 23:08 UTC, anna-stasya commented on model/contacts.js
> +  const result = await Contact.findByIdAndRemove({ _id: contactId, owner: userId })
исправила

2021-11-25 23:08 UTC, anna-stasya commented on model/contacts.js
>    const result = await Contact.findByIdAndUpdate(
исправила

2021-11-26 19:58 UTC, KirillKulakow approved these changes

2021-11-26 21:21 UTC, merged