hw5
anna-stasya/nodejs-REST-API pull request #4
Opened 2021-11-29 00:58 UTC by anna-stasya

2021-11-29 22:22 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
добавить опцию протокола

2021-11-29 22:22 UTC, KirillKulakow commented on controllers/auth/signup.js
> +      // user: {
удалить

2021-11-29 22:23 UTC, KirillKulakow commented on model/Schemas/user.js
> +  image: {
это как?

2021-11-29 22:24 UTC, KirillKulakow commented on routes/api/auth.js
> +router.patch('/avatars', [authenticate, uploadMiddelewares.single('avatar')], controllerWrapper(avatars))
почему все миддлвары в массиве

2021-11-29 22:25 UTC, KirillKulakow requested changes
need fix

2021-11-29 22:54 UTC, anna-stasya commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
добавила

2021-11-29 22:55 UTC, anna-stasya commented on controllers/auth/signup.js
> +      // user: {
убрала

2021-11-29 22:56 UTC, anna-stasya commented on model/Schemas/user.js
> +  image: {
ой, изменила

2021-11-29 22:58 UTC, anna-stasya commented on routes/api/auth.js
> +router.patch('/avatars', [authenticate, uploadMiddelewares.single('avatar')], controllerWrapper(avatars))
убрала

2021-11-30 20:59 UTC, KirillKulakow approved these changes

2021-11-30 22:12 UTC, merged